### ISSUE TITLE
Render client config into HTML instead of embedding in bundle

### ISSUE THREAD

**Issue by ginkoid** [redpwn/rCTF#101]
## Why?
At the moment, we are embedding the client config inside the JS bundle. This means that we cannot distribute rctf Docker images, and that people have to build their own.

## How?
We can move all the client config into a JSON blob rendered into the HTML by the server, allowing us to remove all config from the Docker images. The JSON blob can be derived from the server config.

**Comment by ethanwu10** [comment]
We can also load the blob via a script that runs just before server start and modifies the html file, so that we can use the same script when deploying the frontend to an entirely static server like netlify or nginx.

**Comment by ginkoid** [comment]
Fixed in #251
