### ISSUE TITLE
Use a `Map` for toast lookup

### ISSUE THREAD

**Issue by chen-robert** [redpwn/rctf#130]
We should use a `Map` for the toasts so that we don't have to do this `O(n)` removal?

_Originally posted by @ginkoid in https://github.com/redpwn/rctf/pull/125_

**Comment by ethanwu10** [comment]
There's rarely going to be over 3 toasts on screen at once, I think an O(n) deletion is perfectly fine for n<=3.

**Comment by chen-robert** [comment]
Oh hm, I guess in that case it's probably not an issue.

**Comment by Arinerron** [comment]
![IMG_20200325_104045](https://user-images.githubusercontent.com/3926753/77670724-cf527100-6f43-11ea-9ad6-8b636dc80424.jpg)
