### ISSUE TITLE
Extraneous bundle.esm.js.LICENSE.txt being generated

### ISSUE THREAD

**Issue by ethanwu10** [redpwn/rctf#135]
**Describe the bug**
The current client builds are generating a bundle.esm.js.LICENSE.txt, and it appears the generation is [broken](https://travis-ci.com/github/redpwn/rctf/jobs/306705441#L342) as well (it seems to be attempting to put the header for the actual bundle and the contents of the LICENSE comments into the LICENSE.txt file). My best guess is that this is being produced by the Terser plugin, however it should not attempt to output to the file twice, we don't have any license comments in our source for it to keep, and preact-cli appears to have this behavior [disabled](https://github.com/preactjs/preact-cli/blob/0cf86aa3aa1e5f4c7458875e1d9ef24c7bb85092/packages/cli/lib/lib/webpack/webpack-client-config.js#L207). 

**To Reproduce**
1. Build the client

**Expected behavior**
No webpack warnings are emitted

**Comment by chen-robert** [comment]
Closed by #388
