### ISSUE TITLE
Allow multiple email addresses to be tied to a single account

### ISSUE THREAD

**Issue by Arinerron** [redpwn/rCTF#143]
It would be a nice feature to be able to add multiple email addresses to a single account. A single email address would be required to register the account, but after registering, users can add their email addresses and remove them at will (as long as there is always one verified email address tied to the account).

There should be no limits on the number of email addresses you can add, so long as you can verify them all.

The benefits of this feature are:
- if a team member who isn't so smart goes and clicks the "regenerate team token button" and locks everyone out of the account, the team doesn't have to wait for the account owner to wake up to recover the account or anything. There are lots of convenience benefits for this for users.
- if a team wins prizes but is hard to contact at a single address, we now have the email addresses of everyone on the team; that is, we know *who* is on a team if users opt to give us that information.
- we could possibly collect more email addresses if we use them for notifying about the next RedpwnCTF

**Comment by Arinerron** [comment]
Additionally, per #122, only the primary email address (the one who registered the account originally) should be able to delete the account. This way, if an attacker gets access to the team token because it is leaked in some way, he/she cannot simply add a new email address and verify the deletion request.

**Comment by ginkoid** [comment]
Fixed in #209
