### ISSUE TITLE
UI changes for index and sponsors pages

### ISSUE THREAD

**Issue by Arinerron** [redpwn/rCTF#145]
- [ ] For the sake of simplicity, I think it's best to move the dynamically generated sponsors info page to the bottom of the index/home page. The sponsors info currently disappears when you login, but...
- [ ] ...we should make the home page always accessible, even after logging in. It should be on the left side of the navbar. This page is where the CTF description, rules, etc would go. IMO is makes sense to keep this meta together.

**Comment by ethanwu10** [comment]
Fixed by #280 
/close
