### ISSUE TITLE
Poor performance when resizing scoreboard graph

### ISSUE THREAD

**Issue by ethanwu10** [redpwn/rctf#189]
**Describe the bug**
When the scoreboard page is resized, there is poor performance due to long layouts caused by updating the viewbox of the graph every frame of the resize.

**To Reproduce**
1. Go to `/scores`
2. Resize the window
3. Observe frame timings and layout timings in devtools performance profiler

**Expected behavior**
The page should redraw at 60fps while it is being resized.

**Potential solutions**
- Do not use viewbox to render the graph - this appears to yield about a 2x improvement on layout times (however somehow this also resulted in a ~10x speedup on one of my machines that seems to do particularly bad at updating the viewbox)
- Throttle updates to the graph due to resize events, and scale it in between updates with viewbox. This may still appear janky, but should allow the rest of the page to render at a consistent 60fps.

**Comment by chen-robert** [comment]
Closed by #388
