### ISSUE TITLE
Misleading responses on `/auth/verify`

### ISSUE THREAD

**Issue by chen-robert** [redpwn/rctf#22]
The verification API currently returns `responses.badKnownEmail` on any error. We should only return this on violation of the uniqueness constraint for `email`. 

https://github.com/redpwn/rctf/blob/master/server/api/auth-verify.js#L45

We should also return a similar error for a violation on `name`. You can add a response to https://github.com/redpwn/rctf/blob/master/server/responses/index.js#L1 as `badKnownName`. 

For other database errors, you should return `responses.errorInternal`.

**Comment by jimmyl02** [comment]
Auth-verify should return errorInternal for everything the makeUser catches because the uniqueness verifications hould be done in auth-submit.

**Comment by chen-robert** [comment]
The users don't actually get added to the database until verification, so there can be multiple auth tokens generated for the same name / email. We sould still have to check in the verification endpoint, but we can probably return a generic `badValidation` error with more details in the `data`.

**Comment by jimmyl02** [comment]
Fixed via #35
