### ISSUE TITLE
Set `document.title` from RCTF_NAME

### ISSUE THREAD

**Issue by ginkoid** [redpwn/rCTF#27]
At the moment, we are hardcoding `document.title` in the JS bundle: https://github.com/redpwn/rctf/blob/ad637da2dbe7488d383982cf5ebd49eb9102d8ba/client/src/config.js#L3

It would be better if we read this value from the `RCTF_NAME` env var instead.

**Comment by pepsipu** [comment]
Not gonna lie homie but this do be looking kind of implemented [here](https://github.com/redpwn/rctf/blob/master/config/server.jsl) doe :flushed: :100:

**Comment by chen-robert** [comment]
Yup, we just need to implement it on the client config as well, `config/client.js`.

**Comment by ethanwu10** [comment]
Fixed by #251
