### ISSUE TITLE
Potentially cacheable HTTP responses

### ISSUE THREAD

**Issue by Arinerron** [redpwn/rctf#339]
HTTP responses from endpoints like `/api/v1/users/me` might be cacheable in some browsers. We should throw in these headers to prevent browsers from caching sensitive endpoints:

```http
Pragma: no-cache
Cache-Control: no-store
```

**Comment by chen-robert** [comment]
[RFC compliant](https://tools.ietf.org/html/rfc7234#section-3) caches should not cache endpoints that have the Authorization header set, which would prevent caching behavior on any of our sensitive API endpoints.
