### ISSUE TITLE
Install fails on Ubuntu 20

### ISSUE THREAD

**Issue by DreadnaughtSec** [redpwn/rCTF#381]
**Describe the bug**
The install script fails due to missing files. Manual install fails as well after replacing the missing example.js.

**To Reproduce**
1. Fresh Ubuntu 20.04 install
2. apt-get full-upgrade
3. ./install.configure.sh or curl 

**Expected behavior**
Install succeeds without error.

**Script install**
curl https://get.rctf.redpwn.net | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
....########......######.....########....########...
....##.....##....##....##.......##.......##.........
....##.....##....##.............##.......##.........
....########.....##.............##.......######.....
....##...##......##.............##.......##.........
....##....##.....##....##.......##.......##.........
....##.....##.....######........##.......##.........

[*] Checking environment...
100  4394    0  4394    0     0  13077      0 --:--:-- --:--:-- --:--:-- 13077
[*] Configuring installation...
[*] Installing dependencies...
Hit:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://ppa.launchpad.net/ondrej/nginx-mainline/ubuntu focal InRelease
Hit:5 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:6 http://ppa.launchpad.net/ondrej/php/ubuntu focal InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
git is already the newest version (1:2.25.1-1ubuntu3).
python3 is already the newest version (3.8.2-0ubuntu2).
docker-compose is already the newest version (1.25.0-1).
docker.io is already the newest version (19.03.8-0ubuntu1).
python3-pip is already the newest version (20.0.2-5ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Collecting requests
  Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 623 kB/s
Collecting envparse
  Downloading envparse-0.2.0.tar.gz (7.6 kB)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests) (2019.11.28)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3/dist-packages (from requests) (1.25.8)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests) (2.8)
Building wheels for collected packages: envparse
  Building wheel for envparse (setup.py) ... done
  Created wheel for envparse: filename=envparse-0.2.0-py2.py3-none-any.whl size=7009 sha256=6a29812e52c33fab6eb3a5f73ccf6273f38a333edb6aa5970fa6d3d14dcf2dd8
  Stored in directory: /root/.cache/pip/wheels/76/9c/3a/65bc2654628ca3e0df9bb430847a6d2c859191ffba5b32aa1b
Successfully built envparse
Installing collected packages: requests, envparse
  Attempting uninstall: requests
    Found existing installation: requests 2.22.0
    Not uninstalling requests at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'requests'. No files were found to uninstall.
Successfully installed envparse-0.2.0 requests-2.24.0
[*] Enabling docker...
[*] Cloning repository to /opt/rctf from repository https://github.com/redpwn/rctf.git branch master...
Cloning into '/opt/rctf'...
remote: Enumerating objects: 224, done.
remote: Counting objects: 100% (224/224), done.
remote: Compressing objects: 100% (163/163), done.
remote: Total 7343 (delta 132), reused 108 (delta 59), pack-reused 7119
Receiving objects: 100% (7343/7343), 3.76 MiB | 5.34 MiB/s, done.
Resolving deltas: 100% (4648/4648), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
[*] Configuring rCTF...
cp: cannot stat 'config/client.js.example': No such file or directory

**Manual install**
 ./install/config.sh
WARNING: The RCTF_DATABASE_PASSWORD variable is not set. Defaulting to a blank string.
redis uses an image, skipping
postgres uses an image, skipping
Building rctf
Step 1/13 : FROM node:12.16.3-buster-slim AS build
 ---> b3d2a7266fed
Step 2/13 : WORKDIR /app
 ---> Using cache
 ---> 8a40914683ca
Step 3/13 : COPY package.json yarn.lock ./
 ---> Using cache
 ---> 4597c5c54ec1
Step 4/13 : RUN yarn install --frozen-lockfile && yarn cache clean
 ---> Using cache
 ---> 282aaba71b30
Step 5/13 : COPY . .
 ---> Using cache
 ---> e0ec643e6156
Step 6/13 : RUN yarn build
 ---> Using cache
 ---> 43fed0ca65d4
Step 7/13 : FROM node:12.16.3-buster-slim AS run
 ---> b3d2a7266fed
Step 8/13 : WORKDIR /app
 ---> Using cache
 ---> 8a40914683ca
Step 9/13 : COPY --from=build /app/yarn.lock /app/package.json /app/
 ---> Using cache
 ---> 72e87746a70e
Step 10/13 : ENV NODE_ENV production
 ---> Using cache
 ---> 1faaaf96e404
Step 11/13 : RUN yarn install --prod --frozen-lockfile && yarn cache clean
 ---> Using cache
 ---> 73d6dfd65d09
Step 12/13 : COPY --from=build /app/dist /app/dist
 ---> Using cache
 ---> 3fcd8fba766b
Step 13/13 : CMD ["node", "--enable-source-maps", "--unhandled-rejections=strict", "/app/dist/server/index.js"]
 ---> Using cache
 ---> 5e1a34c39285
Successfully built 5e1a34c39285
Successfully tagged rctf_rctf:latest
WARNING: The RCTF_DATABASE_PASSWORD variable is not set. Defaulting to a blank string.
Starting rctf_postgres_1 ... done
Starting rctf_redis_1    ... done
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module '/app/install/docker-migrate.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Additional context**
The missing example config was replaced by copying client.js to client.js.example.

**Comment by chen-robert** [comment]
Thanks for reporting this @DreadnaughtSec. The installation script has become desynced from the actual repository, but we'll be resolving this shortly.

**Comment by ginkoid** [comment]
This should be fixed now. Let me know if there's any issues.

To reinstall, run `rm -rf /opt/rctf` and run the script again with `curl https://get.rctf.redpwn.net | sudo sh`.
