### ISSUE TITLE
Optimize font loading

### ISSUE THREAD

**Issue by chen-robert** [redpwn/rCTF#47]
We should optimize the fonts we are importing, removing all non-ascii chars to decrease bundle size. 

We might also want to make font loading configurable, with sane fallback system fonts.

**Comment by jimmyl02** [comment]
We could implement https://github.com/patrickhulce/fontmin-webpack in order to reduce font sizes however this isn't a high priority.

**Comment by ginkoid** [comment]
We now use system fonts as of 0a84ee9236c004ed4a669f0c61003a36982c8357.
