### ISSUE TITLE
IPFS storage backend

### ISSUE THREAD

**Issue by karmanyaahm** [redpwn/rctf#579]
**Is your feature request related to a problem? Please describe.**
Totally speculative, but an IPFS storage backend might be nice. It also lets people verify whether they have the latest files and all the content addressed goodness. Perhaps even loading `/challs` from IPFS since it (seems) mostly constant.

**Describe the solution you'd like**
No solution required from rCTF maintainers. I might code this myself someday, but I'm just opening this issue to share the idea.

**Additional Context**
Such storage could be coupled with either multiple round-robined IPFS gateways, or an IPFS client embedded in the frontend; the latter is probably much more difficult. Such decoupling of the challenges - at least ones that don't require a server to run - from the frontend and the scoring system could help make CTFs a lot more permanent for practice purposes.

**Comment by karmanyaahm** [comment]
I have a working solution here [1]. Would rctf be interested in adding this? If so, I could add docs and PR this. 

With this provider the process is exactly the same for end users, except people who use IPFS (the companion browser extension) automatically reduce the load on the servers and seed to the network. On the server side, it's possible to offload file downloading to cloudflare-ipfs, ipfs.io or a cluster of self-hosted IPFS gateways by just specifying the gateway configuration option.

[1] https://github.com/karmanyaahm/rctf/commit/0f5949c7bae031435ceaa566640b816df8621edc

**Comment by ginkoid** [comment]
IPFS could definitely be a good option to reduce server load. However, I think the majority of rCTF installs would not use IPFS, especially as a production setup with GCS can easily handle the bandwidth with minimal costs.

You can PR this, but we don't want to run a [IPFS container](https://github.com/karmanyaahm/rctf/blob/feature/ipfs/docker-compose.yml#L38-L47) when the IPFS feature isn't enabled. Removing that container and making the rCTF operator responsible for externally running `ipfs/go-ipfs` would make the most sense to me.

**Comment by karmanyaahm** [comment]
My plan of hosting a CTF was unfortunately cancelled, so I won't be using this. So I'm closing this issue and associated PR. Thanks for your time.
